services:
  backend:
    build:
      context: ./backend
    container_name: agent-backend-app
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agent-frontend-app
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
 
 
